name: Kamal Deploy
description: GitHub Action to build and deploy Docker image with Kamal
color: 'blue'
inputs:
  environment:
    description: 'Application environment will be passed to Kamal as --destination flag'
    required: true
  registry-username:
    description: 'Registry username'
    required: true
  registry-password:
    description: 'Registry password'
    required: true
runs:
  using: 'node20'
  main: 'index.js'

branding:
  icon: 'anchor'
  color: 'blue'